# Don't define "links" between services.   They aren't necessary and they break load balancing if you later
# scale up the storage nodes.
version: '2.1'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.2.5
    command: >
      -name etcd0
      -advertise-client-urls http://etcd:2379,http://etcd:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster etcd0=http://etcd:2380
      -initial-cluster-state new
  astaire:
    image: m0rf30/clearwater-astaire
    build: astaire
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  chronos:
    image: m0rf30/clearwater-chronos
    build: chronos
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  cassandra:
    image: m0rf30/clearwater-cassandra
    sysctls:
       net.ipv6.conf.lo.disable_ipv6: 0
    build: cassandra
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  bono:
    image: m0rf30/clearwater-bono
    build: bono
    environment:
      - PUBLIC_IP
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
      - "3478:3478"
      - "3478:3478/udp"
      - "5060:5060"
      - "5060:5060/udp"
      - "5062:5062"
  sprout:
    image: m0rf30/clearwater-sprout
    build: sprout
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  homestead:
    image: m0rf30/clearwater-homestead
    build: homestead
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  homestead-prov:
    image: m0rf30/clearwater-homestead-prov
    build: homestead-prov
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  homer:
    image: m0rf30/clearwater-homer
    build: homer
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  ralf:
    image: m0rf30/clearwater-ralf
    build: ralf
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
  ellis:
    image: m0rf30/clearwater-ellis
    build: ellis
    environment:
      - ADDITIONAL_SHARED_CONFIG
    ports:
      - 22
      - "80:80"
